### ISSUE TITLE
Release it for real

### ISSUE THREAD

**Issue by justanr** [flaskbb/flask-debugtoolbar-warnings#1]
Only took six tries, MANIFEST.in is no joke. :/

But I can run it installed from pypi (install with `pip install --pre flask-debugtoolbar-warnings`). Is there anything we should do before making it not a pre-release install, @sh4nks ?

**Comment by sh4nks** [comment]
Haha, I feel your pain :P

I didn't find anything besides the empty changelog :)

**Comment by justanr** [comment]
Filled that and the authors portion out. I'll leave this open for a bit longer in case we think of anything, otherwise I'll probably do the release Monday or Tuesday.

**Comment by justanr** [comment]
Pushed out v0.1.0 just now.
